name: ai_poetry_card
description: 拾光记 - 为你的瞬间配上有灵魂的文字

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & 动画
  cupertino_icons: ^1.0.2
  flutter_slidable: ^3.1.0
  
  # 图片处理
  image_picker: ^1.0.4
  image: ^4.1.3
  
  # 二维码
  qr_flutter: ^4.1.0
  
  # 状态管理
  provider: ^6.1.1
  
  # 国际化
  flutter_localizations:
    sdk: flutter
  
  # 本地存储
  shared_preferences: ^2.2.2
  path: ^1.8.3
  
  # 网络请求
  dio: ^5.4.0
  
  # 腾讯云 COS SDK
  tencentcloud_cos_sdk_plugin: ^1.2.6
  
  # 工具类
  intl: ^0.20.2
  permission_handler: ^11.0.1
  flutter_dotenv: ^5.1.0
  
  # 位置服务
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # 地图
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  
  # 设备信息
  device_info_plus: ^10.1.0
  package_info_plus: ^4.2.0
  
  # 加密
  encrypt: ^5.0.1
  crypto: ^3.0.3
  
  # 内购
  purchases_flutter: ^8.5.2
  purchases_ui_flutter: ^8.5.2
  
  # 分享功能
  share_plus: ^7.2.2
  url_launcher: ^6.2.2
  # 原生分享方案
  platform: ^3.1.0
  
  # 文件操作
  path_provider: ^2.1.1
  
  # 相册管理
  gal: ^2.3.0
  
  # 注释：使用 gal 插件管理相册权限和保存功能
  
  # Lottie动画
  lottie: ^3.1.2
  
  # Excel导出
  excel: ^4.0.3
  
  # 友盟统计
  fl_umeng: ^4.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/fonts/
    - assets/animation/
    - assets/images/vip.png
    - assets/images/weibo_vip.png
    - assets/images/xiaohongshu_share.png
    - assets/images/douyin_share.png
    - assets/images/weixin_love.png
    - assets/images/phone_border.png
    - assets/images/avatar.png
    - assets/images/weibo_share.jpg
    - assets/images/duilian.png
    - assets/images/appName_zh.png
    - assets/images/appName_en.png
    
    - .env
  
  fonts:
    - family: JiangxiZhuokai
      fonts:
        - asset: assets/fonts/JiangxiZhuokai-Regular.ttf
          weight: 400
        - asset: assets/fonts/JiangxiZhuokai-Bold.ttf
          weight: 700
    - family: JiangchengLvdongsong
      fonts:
        - asset: assets/fonts/jiangchenglvdongsong.ttf
          weight: 400
    - family: YanShiXiaXingKai
      fonts:
        - asset: assets/fonts/YanShiXiaXingKai-2.ttf
          weight: 600

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
  macos:
    generate: true
    image_path: "assets/images/logo.png"
